apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafanaalertrulegroups.grafana.integreatly.org.yaml
- grafanacontactpoints.grafana.integreatly.org.yaml
- grafanadashboards.grafana.integreatly.org.yaml
- grafanadatasources.grafana.integreatly.org.yaml
- grafanafolders.grafana.integreatly.org.yaml
- grafanalibrarypanels.grafana.integreatly.org.yaml
- grafanamanifests.grafana.integreatly.org.yaml
- grafanamutetimings.grafana.integreatly.org.yaml
- grafananotificationpolicies.grafana.integreatly.org.yaml
- grafananotificationpolicyroutes.grafana.integreatly.org.yaml
- grafananotificationtemplates.grafana.integreatly.org.yaml
- grafanas.grafana.integreatly.org.yaml
- grafanaserviceaccounts.grafana.integreatly.org.yaml
