apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- miroirnodegroups.miroir.home-operations.com.yaml
- miroirnodes.miroir.home-operations.com.yaml
- miroirsnapshotgroups.miroir.home-operations.com.yaml
- miroirsnapshots.miroir.home-operations.com.yaml
- miroirvolumes.miroir.home-operations.com.yaml
