apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bindings.rabbitmq.com.yaml
- exchanges.rabbitmq.com.yaml
- federations.rabbitmq.com.yaml
- operatorpolicies.rabbitmq.com.yaml
- permissions.rabbitmq.com.yaml
- policies.rabbitmq.com.yaml
- queues.rabbitmq.com.yaml
- schemareplications.rabbitmq.com.yaml
- shovels.rabbitmq.com.yaml
- superstreams.rabbitmq.com.yaml
- topicpermissions.rabbitmq.com.yaml
- users.rabbitmq.com.yaml
- vhosts.rabbitmq.com.yaml
