apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kafkabridges.kafka.strimzi.io.yaml
- kafkaconnectors.kafka.strimzi.io.yaml
- kafkaconnects.kafka.strimzi.io.yaml
- kafkamirrormaker2s.kafka.strimzi.io.yaml
- kafkanodepools.kafka.strimzi.io.yaml
- kafkarebalances.kafka.strimzi.io.yaml
- kafkas.kafka.strimzi.io.yaml
- kafkatopics.kafka.strimzi.io.yaml
- kafkausers.kafka.strimzi.io.yaml
- strimzipodsets.core.strimzi.io.yaml
