apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterproxies.netbird.io.yaml
- groups.netbird.io.yaml
- nbgroups.netbird.io.yaml
- nbpolicies.netbird.io.yaml
- nbresources.netbird.io.yaml
- nbroutingpeers.netbird.io.yaml
- nbsetupkeys.netbird.io.yaml
- networkegresses.netbird.io.yaml
- networkresources.netbird.io.yaml
- networkrouters.netbird.io.yaml
- setupkeys.netbird.io.yaml
- sidecarprofiles.netbird.io.yaml
