apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bfdprofiles.metallb.io.yaml
- bgpadvertisements.metallb.io.yaml
- bgppeers.metallb.io.yaml
- communities.metallb.io.yaml
- configurationstates.metallb.io.yaml
- ipaddresspools.metallb.io.yaml
- l2advertisements.metallb.io.yaml
- servicebgpstatuses.metallb.io.yaml
- servicel2statuses.metallb.io.yaml
