apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- accesstunnels.networking.cfargotunnel.com.yaml
- clustertunnels.networking.cfargotunnel.com.yaml
- tunnelbindings.networking.cfargotunnel.com.yaml
- tunnels.networking.cfargotunnel.com.yaml
