apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- lvmnodes.local.openebs.io.yaml
- lvmsnapshots.local.openebs.io.yaml
- lvmvolumes.local.openebs.io.yaml
- zfsbackups.zfs.openebs.io.yaml
- zfsnodes.zfs.openebs.io.yaml
- zfsrestores.zfs.openebs.io.yaml
- zfssnapshots.zfs.openebs.io.yaml
- zfsvolumes.zfs.openebs.io.yaml
