apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clustermongodbroles.mongodb.com.yaml
- mongodb.mongodb.com.yaml
- mongodbcommunity.mongodbcommunity.mongodb.com.yaml
- mongodbmulticluster.mongodb.com.yaml
- mongodbsearch.mongodb.com.yaml
- mongodbusers.mongodb.com.yaml
- opsmanagers.mongodb.com.yaml
- voyageais.ai.mongodb.com.yaml
