apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pgadmins.postgres-operator.crunchydata.com.yaml
- pgupgrades.postgres-operator.crunchydata.com.yaml
- postgresclusters.postgres-operator.crunchydata.com.yaml
