apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterusages.protection.crossplane.io.yaml
- compositeresourcedefinitions.apiextensions.crossplane.io.yaml
- compositionrevisions.apiextensions.crossplane.io.yaml
- compositions.apiextensions.crossplane.io.yaml
- configurationrevisions.pkg.crossplane.io.yaml
- configurations.pkg.crossplane.io.yaml
- cronoperations.ops.crossplane.io.yaml
- deploymentruntimeconfigs.pkg.crossplane.io.yaml
- environmentconfigs.apiextensions.crossplane.io.yaml
- functionrevisions.pkg.crossplane.io.yaml
- functions.pkg.crossplane.io.yaml
- imageconfigs.pkg.crossplane.io.yaml
- locks.pkg.crossplane.io.yaml
- managedresourceactivationpolicies.apiextensions.crossplane.io.yaml
- managedresourcedefinitions.apiextensions.crossplane.io.yaml
- operations.ops.crossplane.io.yaml
- providerrevisions.pkg.crossplane.io.yaml
- providers.pkg.crossplane.io.yaml
- usages.apiextensions.crossplane.io.yaml
- usages.protection.crossplane.io.yaml
- watchoperations.ops.crossplane.io.yaml
