apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cephblockpoolradosnamespaces.ceph.rook.io.yaml
- cephblockpools.ceph.rook.io.yaml
- cephbucketnotifications.ceph.rook.io.yaml
- cephbuckettopics.ceph.rook.io.yaml
- cephclients.ceph.rook.io.yaml
- cephclusters.ceph.rook.io.yaml
- cephconnections.csi.ceph.io.yaml
- cephcosidrivers.ceph.rook.io.yaml
- cephfilesystemmirrors.ceph.rook.io.yaml
- cephfilesystems.ceph.rook.io.yaml
- cephfilesystemsubvolumegroups.ceph.rook.io.yaml
- cephnfses.ceph.rook.io.yaml
- cephnvmeofgateways.ceph.rook.io.yaml
- cephobjectrealms.ceph.rook.io.yaml
- cephobjectstores.ceph.rook.io.yaml
- cephobjectstoreusers.ceph.rook.io.yaml
- cephobjectzonegroups.ceph.rook.io.yaml
- cephobjectzones.ceph.rook.io.yaml
- cephrbdmirrors.ceph.rook.io.yaml
- clientprofilemappings.csi.ceph.io.yaml
- clientprofiles.csi.ceph.io.yaml
- drivers.csi.ceph.io.yaml
- objectbucketclaims.objectbucket.io.yaml
- objectbuckets.objectbucket.io.yaml
- operatorconfigs.csi.ceph.io.yaml
