apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- connectors.tailscale.com.yaml
- dnsconfigs.tailscale.com.yaml
- proxyclasses.tailscale.com.yaml
- proxygrouppolicies.tailscale.com.yaml
- proxygroups.tailscale.com.yaml
- recorders.tailscale.com.yaml
- tailnets.tailscale.com.yaml
