apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vlagents.operator.victoriametrics.com.yaml
- vlclusters.operator.victoriametrics.com.yaml
- vlogs.operator.victoriametrics.com.yaml
- vlsingles.operator.victoriametrics.com.yaml
- vmagents.operator.victoriametrics.com.yaml
- vmalertmanagerconfigs.operator.victoriametrics.com.yaml
- vmalertmanagers.operator.victoriametrics.com.yaml
- vmalerts.operator.victoriametrics.com.yaml
- vmanomalies.operator.victoriametrics.com.yaml
- vmauths.operator.victoriametrics.com.yaml
- vmclusters.operator.victoriametrics.com.yaml
- vmdistributed.operator.victoriametrics.com.yaml
- vmnodescrapes.operator.victoriametrics.com.yaml
- vmpodscrapes.operator.victoriametrics.com.yaml
- vmprobes.operator.victoriametrics.com.yaml
- vmrules.operator.victoriametrics.com.yaml
- vmscrapeconfigs.operator.victoriametrics.com.yaml
- vmservicescrapes.operator.victoriametrics.com.yaml
- vmsingles.operator.victoriametrics.com.yaml
- vmstaticscrapes.operator.victoriametrics.com.yaml
- vmusers.operator.victoriametrics.com.yaml
- vtclusters.operator.victoriametrics.com.yaml
- vtsingles.operator.victoriametrics.com.yaml
