apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- embeddingservers.toolhive.stacklok.dev.yaml
- mcpauthzconfigs.toolhive.stacklok.dev.yaml
- mcpexternalauthconfigs.toolhive.stacklok.dev.yaml
- mcpgroups.toolhive.stacklok.dev.yaml
- mcpoidcconfigs.toolhive.stacklok.dev.yaml
- mcpregistries.toolhive.stacklok.dev.yaml
- mcpremoteproxies.toolhive.stacklok.dev.yaml
- mcpserverentries.toolhive.stacklok.dev.yaml
- mcpservers.toolhive.stacklok.dev.yaml
- mcptelemetryconfigs.toolhive.stacklok.dev.yaml
- mcptoolconfigs.toolhive.stacklok.dev.yaml
- mcpwebhookconfigs.toolhive.stacklok.dev.yaml
- virtualmcpcompositetooldefinitions.toolhive.stacklok.dev.yaml
- virtualmcpservers.toolhive.stacklok.dev.yaml
