apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- acceleratorfunctions.fpga.intel.com.yaml
- dlbdeviceplugins.deviceplugin.intel.com.yaml
- dsadeviceplugins.deviceplugin.intel.com.yaml
- fpgadeviceplugins.deviceplugin.intel.com.yaml
- fpgaregions.fpga.intel.com.yaml
- gpudeviceplugins.deviceplugin.intel.com.yaml
- iaadeviceplugins.deviceplugin.intel.com.yaml
- npudeviceplugins.deviceplugin.intel.com.yaml
- qatdeviceplugins.deviceplugin.intel.com.yaml
- sgxdeviceplugins.deviceplugin.intel.com.yaml
