apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- aliases.lambda.services.k8s.aws.yaml
- codesigningconfigs.lambda.services.k8s.aws.yaml
- eventsourcemappings.lambda.services.k8s.aws.yaml
- fieldexports.services.k8s.aws.yaml
- functions.lambda.services.k8s.aws.yaml
- functionurlconfigs.lambda.services.k8s.aws.yaml
- iamroleselectors.services.k8s.aws.yaml
- layerversions.lambda.services.k8s.aws.yaml
- versions.lambda.services.k8s.aws.yaml
