apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agentgatewaybackends.agentgateway.dev.yaml
- agentgatewayparameters.agentgateway.dev.yaml
- agentgatewaypolicies.agentgateway.dev.yaml
