apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agentictasks.foreman.llmkube.dev.yaml
- agentreleases.foreman.llmkube.dev.yaml
- agents.foreman.llmkube.dev.yaml
- fleetnodes.foreman.llmkube.dev.yaml
- modelprofiles.foreman.llmkube.dev.yaml
- workloads.foreman.llmkube.dev.yaml
