apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- csiaddonsnodes.csiaddons.openshift.io.yaml
- encryptionkeyrotationcronjobs.csiaddons.openshift.io.yaml
- encryptionkeyrotationjobs.csiaddons.openshift.io.yaml
- networkfenceclasses.csiaddons.openshift.io.yaml
- networkfences.csiaddons.openshift.io.yaml
- reclaimspacecronjobs.csiaddons.openshift.io.yaml
- reclaimspacejobs.csiaddons.openshift.io.yaml
- volumegroupreplicationclasses.replication.storage.openshift.io.yaml
- volumegroupreplicationcontents.replication.storage.openshift.io.yaml
- volumegroupreplications.replication.storage.openshift.io.yaml
- volumereplicationclasses.replication.storage.openshift.io.yaml
- volumereplications.replication.storage.openshift.io.yaml
