apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ippools.whereabouts.cni.cncf.io.yaml
- nodeslicepools.whereabouts.cni.cncf.io.yaml
- overlappingrangeipreservations.whereabouts.cni.cncf.io.yaml
