apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manualapprovalgates.operator.tekton.dev.yaml
- openshiftpipelinesascodes.operator.tekton.dev.yaml
- syncerservices.operator.tekton.dev.yaml
- tektonchains.operator.tekton.dev.yaml
- tektonconfigs.operator.tekton.dev.yaml
- tektondashboards.operator.tekton.dev.yaml
- tektoninstallersets.operator.tekton.dev.yaml
- tektonmulticlusterproxyaaes.operator.tekton.dev.yaml
- tektonpipelines.operator.tekton.dev.yaml
- tektonpruners.operator.tekton.dev.yaml
- tektonresults.operator.tekton.dev.yaml
- tektonschedulers.operator.tekton.dev.yaml
- tektontriggers.operator.tekton.dev.yaml
