apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps.direwolf.games-on-whales.github.io.yaml
- pairings.direwolf.games-on-whales.github.io.yaml
- sessions.direwolf.games-on-whales.github.io.yaml
- users.direwolf.games-on-whales.github.io.yaml
