apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agents.dispatch.janpuc.com.yaml
- sessions.dispatch.janpuc.com.yaml
- triggers.dispatch.janpuc.com.yaml
- workspaces.dispatch.janpuc.com.yaml
