apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- chains.ai.roundtable.io.yaml
- knights.ai.roundtable.io.yaml
- missions.ai.roundtable.io.yaml
- roundtables.ai.roundtable.io.yaml
