apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterkopfpeerings.zalando.org.yaml
- innodbclusters.mysql.oracle.com.yaml
- kopfpeerings.zalando.org.yaml
- mysqlbackups.mysql.oracle.com.yaml
- mysqlclustersetfailovers.mysql.oracle.com.yaml
