apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dataplanes.stunner.l7mp.io.yaml
- gatewayconfigs.stunner.l7mp.io.yaml
- staticservices.stunner.l7mp.io.yaml
- udproutes.stunner.l7mp.io.yaml
