apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrepositories.kopiur.home-operations.com.yaml
- maintenances.kopiur.home-operations.com.yaml
- repositories.kopiur.home-operations.com.yaml
- repositoryreplications.kopiur.home-operations.com.yaml
- restores.kopiur.home-operations.com.yaml
- snapshotpolicies.kopiur.home-operations.com.yaml
- snapshotreplications.kopiur.home-operations.com.yaml
- snapshots.kopiur.home-operations.com.yaml
- snapshotschedules.kopiur.home-operations.com.yaml
