apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backendconfigpolicies.gateway.kgateway.dev.yaml
- backends.gateway.kgateway.dev.yaml
- directresponses.gateway.kgateway.dev.yaml
- gatewayextensions.gateway.kgateway.dev.yaml
- gatewayparameters.gateway.kgateway.dev.yaml
- httplistenerpolicies.gateway.kgateway.dev.yaml
- listenerpolicies.gateway.kgateway.dev.yaml
- trafficpolicies.gateway.kgateway.dev.yaml
