apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ipaddressclaims.netbox.dev.yaml
- ipaddresses.netbox.dev.yaml
- iprangeclaims.netbox.dev.yaml
- ipranges.netbox.dev.yaml
- prefixclaims.netbox.dev.yaml
- prefixes.netbox.dev.yaml
