apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- litellmguardrails.litellm.home-operations.com.yaml
- litellmmcpservers.litellm.home-operations.com.yaml
- litellmmodels.litellm.home-operations.com.yaml
- litellmproxies.litellm.home-operations.com.yaml
- litellmteams.litellm.home-operations.com.yaml
- litellmvirtualkeys.litellm.home-operations.com.yaml
