apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clustercompliancereports.aquasecurity.github.io.yaml
- clusterconfigauditreports.aquasecurity.github.io.yaml
- clusterinfraassessmentreports.aquasecurity.github.io.yaml
- clusterrbacassessmentreports.aquasecurity.github.io.yaml
- clustersbomreports.aquasecurity.github.io.yaml
- clustervulnerabilityreports.aquasecurity.github.io.yaml
- configauditreports.aquasecurity.github.io.yaml
- exposedsecretreports.aquasecurity.github.io.yaml
- infraassessmentreports.aquasecurity.github.io.yaml
- rbacassessmentreports.aquasecurity.github.io.yaml
- sbomreports.aquasecurity.github.io.yaml
- vulnerabilityreports.aquasecurity.github.io.yaml
