apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- accountings.slinky.slurm.net.yaml
- controllers.slinky.slurm.net.yaml
- loginsets.slinky.slurm.net.yaml
- nodesets.slinky.slurm.net.yaml
- restapis.slinky.slurm.net.yaml
- tokens.slinky.slurm.net.yaml
