apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authenticationfilters.gateway.nginx.org.yaml
- clientsettingspolicies.gateway.nginx.org.yaml
- externalloadbalancers.gateway.nginx.org.yaml
- nginxgateways.gateway.nginx.org.yaml
- nginxproxies.gateway.nginx.org.yaml
- observabilitypolicies.gateway.nginx.org.yaml
- payloadprocessors.gateway.nginx.org.yaml
- proxysettingspolicies.gateway.nginx.org.yaml
- ratelimitpolicies.gateway.nginx.org.yaml
- snippetsfilters.gateway.nginx.org.yaml
- snippetspolicies.gateway.nginx.org.yaml
- upstreamsettingspolicies.gateway.nginx.org.yaml
- wafpolicies.gateway.nginx.org.yaml
