apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- admissionpolicies.policies.kubewarden.io.yaml
- admissionpolicygroups.policies.kubewarden.io.yaml
- clusteradmissionpolicies.policies.kubewarden.io.yaml
- clusteradmissionpolicygroups.policies.kubewarden.io.yaml
- clusterreports.openreports.io.yaml
- policyservers.policies.kubewarden.io.yaml
- reports.openreports.io.yaml
