apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backups.k8s.mariadb.com.yaml
- connections.k8s.mariadb.com.yaml
- databases.k8s.mariadb.com.yaml
- externalmariadbs.k8s.mariadb.com.yaml
- grants.k8s.mariadb.com.yaml
- mariadbs.k8s.mariadb.com.yaml
- maxscales.k8s.mariadb.com.yaml
- physicalbackups.k8s.mariadb.com.yaml
- pointintimerecoveries.k8s.mariadb.com.yaml
- restores.k8s.mariadb.com.yaml
- sqljobs.k8s.mariadb.com.yaml
- users.k8s.mariadb.com.yaml
