apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- instrumentations.opentelemetry.io.yaml
- opampbridges.opentelemetry.io.yaml
- opentelemetrycollectors.opentelemetry.io.yaml
- podmonitors.monitoring.coreos.com.yaml
- probes.monitoring.coreos.com.yaml
- scrapeconfigs.monitoring.coreos.com.yaml
- servicemonitors.monitoring.coreos.com.yaml
- targetallocators.opentelemetry.io.yaml
