apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafanaagents.monitoring.grafana.com.yaml
- integrations.monitoring.grafana.com.yaml
- logsinstances.monitoring.grafana.com.yaml
- metricsinstances.monitoring.grafana.com.yaml
- podlogs.monitoring.grafana.com.yaml
- podmonitors.monitoring.coreos.com.yaml
- probes.monitoring.coreos.com.yaml
- replicatemplates.rollout-operator.grafana.com.yaml
- servicemonitors.monitoring.coreos.com.yaml
- zoneawarepoddisruptionbudgets.rollout-operator.grafana.com.yaml
