apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterpolicies.nvidia.com.yaml
- computedomaincliques.resource.nvidia.com.yaml
- computedomains.resource.nvidia.com.yaml
- gpuclusters.nvidia.com.yaml
- nvidiadrivers.nvidia.com.yaml
