apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- inferencemodelrewrites.llm-d.ai.yaml
- inferenceobjectives.llm-d.ai.yaml
- inferencepools.inference.networking.k8s.io.yaml
- inferencepools.inference.networking.x-k8s.io.yaml
