apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- aigatewayroutes.aigateway.envoyproxy.io.yaml
- aiservicebackends.aigateway.envoyproxy.io.yaml
- backendsecuritypolicies.aigateway.envoyproxy.io.yaml
- gatewayconfigs.aigateway.envoyproxy.io.yaml
- mcproutes.aigateway.envoyproxy.io.yaml
- quotapolicies.aigateway.envoyproxy.io.yaml
