apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterkeycloakinstances.keycloak.hostzero.com.yaml
- clusterkeycloakrealms.keycloak.hostzero.com.yaml
- keycloakauthenticationflows.keycloak.hostzero.com.yaml
- keycloakclients.keycloak.hostzero.com.yaml
- keycloakclientscopes.keycloak.hostzero.com.yaml
- keycloakcomponents.keycloak.hostzero.com.yaml
- keycloakgroups.keycloak.hostzero.com.yaml
- keycloakidentityprovidermappers.keycloak.hostzero.com.yaml
- keycloakidentityproviders.keycloak.hostzero.com.yaml
- keycloakinstances.keycloak.hostzero.com.yaml
- keycloakorganizations.keycloak.hostzero.com.yaml
- keycloakprotocolmappers.keycloak.hostzero.com.yaml
- keycloakrealms.keycloak.hostzero.com.yaml
- keycloakrequiredactions.keycloak.hostzero.com.yaml
- keycloakrolemappings.keycloak.hostzero.com.yaml
- keycloakroles.keycloak.hostzero.com.yaml
- keycloakusercredentials.keycloak.hostzero.com.yaml
- keycloakusers.keycloak.hostzero.com.yaml
