apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterstoragecontainers.serving.kserve.io.yaml
- llminferenceserviceconfigs.serving.kserve.io.yaml
- llminferenceservices.serving.kserve.io.yaml
