apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- horizontalrunnerautoscalers.actions.summerwind.dev.yaml
- runnerdeployments.actions.summerwind.dev.yaml
- runnerreplicasets.actions.summerwind.dev.yaml
- runners.actions.summerwind.dev.yaml
- runnersets.actions.summerwind.dev.yaml
