apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- assign.mutations.gatekeeper.sh.yaml
- assignimage.mutations.gatekeeper.sh.yaml
- assignmetadata.mutations.gatekeeper.sh.yaml
- configpodstatuses.status.gatekeeper.sh.yaml
- configs.config.gatekeeper.sh.yaml
- connectionpodstatuses.status.gatekeeper.sh.yaml
- connections.connection.gatekeeper.sh.yaml
- constraintpodstatuses.status.gatekeeper.sh.yaml
- constrainttemplatepodstatuses.status.gatekeeper.sh.yaml
- constrainttemplates.templates.gatekeeper.sh.yaml
- expansiontemplate.expansion.gatekeeper.sh.yaml
- expansiontemplatepodstatuses.status.gatekeeper.sh.yaml
- modifyset.mutations.gatekeeper.sh.yaml
- mutatorpodstatuses.status.gatekeeper.sh.yaml
- providerpodstatuses.status.gatekeeper.sh.yaml
- providers.externaldata.gatekeeper.sh.yaml
- syncsets.syncset.gatekeeper.sh.yaml
