apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backups.postgresql.cnpg.io.yaml
- clusterimagecatalogs.postgresql.cnpg.io.yaml
- clusters.postgresql.cnpg.io.yaml
- databases.postgresql.cnpg.io.yaml
- failoverquorums.postgresql.cnpg.io.yaml
- imagecatalogs.postgresql.cnpg.io.yaml
- poolers.postgresql.cnpg.io.yaml
- publications.postgresql.cnpg.io.yaml
- scheduledbackups.postgresql.cnpg.io.yaml
- subscriptions.postgresql.cnpg.io.yaml
