apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agentharnesses.kagent.dev.yaml
- agents.kagent.dev.yaml
- mcpservers.kagent.dev.yaml
- memories.kagent.dev.yaml
- modelconfigs.kagent.dev.yaml
- modelproviderconfigs.kagent.dev.yaml
- remotemcpservers.kagent.dev.yaml
- sandboxagents.kagent.dev.yaml
- toolservers.kagent.dev.yaml
