apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- extensions.t3code.janpuc.com.yaml
- harnesses.t3code.janpuc.com.yaml
- mcpservers.t3code.janpuc.com.yaml
- workstations.t3code.janpuc.com.yaml
