apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cloudeventsources.eventing.keda.sh.yaml
- clustercloudeventsources.eventing.keda.sh.yaml
- clustertriggerauthentications.keda.sh.yaml
- scaledjobs.keda.sh.yaml
- scaledobjects.keda.sh.yaml
- triggerauthentications.keda.sh.yaml
