apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kanidmgroups.kaniop.rs.yaml
- kanidmoauth2clients.kaniop.rs.yaml
- kanidmpersonaccounts.kaniop.rs.yaml
- kanidms.kaniop.rs.yaml
- kanidmserviceaccounts.kaniop.rs.yaml
