---
# discovered by discover-apps: referenced by 3 clusters
# renovate: datasource=docker depName=ghcr.io/prometheus-community/charts/alertmanager
version: 1.41.1
helm:
  chartUrl: oci://ghcr.io/prometheus-community/charts/alertmanager
