---
# renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
version: 0.90.0
fileUrls:
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v${VERSION}/bundle.yaml
