---
# discovered by discover-apps: referenced by 1 clusters
# renovate: datasource=docker depName=ghcr.io/prometheus-community/charts/prometheus-ipmi-exporter
version: 0.8.0
helm:
  chartUrl: oci://ghcr.io/prometheus-community/charts/prometheus-ipmi-exporter
