---
# discovered by discover-apps: referenced by 1 clusters
# renovate: datasource=docker depName=ghcr.io/traefik/helm/traefik-crds
version: 1.18.0
helm:
  chartUrl: oci://ghcr.io/traefik/helm/traefik-crds
