apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingressroutes.traefik.io.yaml
- ingressroutetcps.traefik.io.yaml
- ingressrouteudps.traefik.io.yaml
- middlewares.traefik.io.yaml
- middlewaretcps.traefik.io.yaml
- serverstransports.traefik.io.yaml
- serverstransporttcps.traefik.io.yaml
- tlsoptions.traefik.io.yaml
- tlsstores.traefik.io.yaml
- traefikservices.traefik.io.yaml
