apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mcpgatewayextensions.mcp.kuadrant.io.yaml
- mcpserverregistrations.mcp.kuadrant.io.yaml
- mcpvirtualservers.mcp.kuadrant.io.yaml
