apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- catalogsources.operators.coreos.com.yaml
- clusterserviceversions.operators.coreos.com.yaml
- installplans.operators.coreos.com.yaml
- olmconfigs.operators.coreos.com.yaml
- operatorconditions.operators.coreos.com.yaml
- operatorgroups.operators.coreos.com.yaml
- operators.operators.coreos.com.yaml
- subscriptions.operators.coreos.com.yaml
