apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ciliumbgpadvertisements.cilium.io.yaml
- ciliumbgpclusterconfigs.cilium.io.yaml
- ciliumbgpnodeconfigoverrides.cilium.io.yaml
- ciliumbgpnodeconfigs.cilium.io.yaml
- ciliumbgppeerconfigs.cilium.io.yaml
- ciliumcidrgroups.cilium.io.yaml
- ciliumclusterwideenvoyconfigs.cilium.io.yaml
- ciliumclusterwidenetworkpolicies.cilium.io.yaml
- ciliumegressgatewaypolicies.cilium.io.yaml
- ciliumendpoints.cilium.io.yaml
- ciliumenvoyconfigs.cilium.io.yaml
- ciliumidentities.cilium.io.yaml
- ciliumloadbalancerippools.cilium.io.yaml
- ciliumlocalredirectpolicies.cilium.io.yaml
- ciliumnetworkpolicies.cilium.io.yaml
- ciliumnodeconfigs.cilium.io.yaml
- ciliumnodes.cilium.io.yaml
