apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alertmanagers.sreportal.io.yaml
- components.sreportal.io.yaml
- dns.sreportal.io.yaml
- dnsrecords.sreportal.io.yaml
- flowedgesets.sreportal.io.yaml
- flownodesets.sreportal.io.yaml
- flowobservers.sreportal.io.yaml
- imageinventories.sreportal.io.yaml
- imageregistries.sreportal.io.yaml
- incidents.sreportal.io.yaml
- maintenances.sreportal.io.yaml
- networkflowdiscoveries.sreportal.io.yaml
- portals.sreportal.io.yaml
- releases.sreportal.io.yaml
