apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- garageadmintokens.garage.rajsingh.info.yaml
- garagebuckets.garage.rajsingh.info.yaml
- garageclusters.garage.rajsingh.info.yaml
- garagekeys.garage.rajsingh.info.yaml
- garagenodes.garage.rajsingh.info.yaml
